
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixedFrame;

	private global::Gtk.DrawingArea drawingArea;

	private global::Gtk.ComboBox comboboxColor;

	private global::Gtk.ProgressBar progressbar;

	private global::Gtk.Button buttonResetDraw;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.WidthRequest = 500;
		this.HeightRequest = 300;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DefaultWidth = 1000;
		this.DefaultHeight = 700;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixedFrame = new global::Gtk.Fixed();
		this.fixedFrame.Name = "fixedFrame";
		this.fixedFrame.HasWindow = false;
		// Container child fixedFrame.Gtk.Fixed+FixedChild
		this.drawingArea = new global::Gtk.DrawingArea();
		this.drawingArea.WidthRequest = 900;
		this.drawingArea.HeightRequest = 600;
		this.drawingArea.Name = "drawingArea";
		this.fixedFrame.Add(this.drawingArea);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixedFrame[this.drawingArea]));
		w1.X = 22;
		w1.Y = 18;
		// Container child fixedFrame.Gtk.Fixed+FixedChild
		this.comboboxColor = global::Gtk.ComboBox.NewText();
		this.comboboxColor.AppendText(global::Mono.Unix.Catalog.GetString("Black"));
		this.comboboxColor.AppendText(global::Mono.Unix.Catalog.GetString("White"));
		this.comboboxColor.AppendText(global::Mono.Unix.Catalog.GetString("Yellow"));
		this.comboboxColor.AppendText(global::Mono.Unix.Catalog.GetString("Green"));
		this.comboboxColor.AppendText(global::Mono.Unix.Catalog.GetString("Blue"));
		this.comboboxColor.AppendText(global::Mono.Unix.Catalog.GetString("Red"));
		this.comboboxColor.AppendText(global::Mono.Unix.Catalog.GetString("Pink"));
		this.comboboxColor.AppendText(global::Mono.Unix.Catalog.GetString("Brown"));
		this.comboboxColor.AppendText(global::Mono.Unix.Catalog.GetString("Orange"));
		this.comboboxColor.Name = "comboboxColor";
		this.comboboxColor.Active = 0;
		this.fixedFrame.Add(this.comboboxColor);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixedFrame[this.comboboxColor]));
		w2.X = 28;
		w2.Y = 654;
		// Container child fixedFrame.Gtk.Fixed+FixedChild
		this.progressbar = new global::Gtk.ProgressBar();
		this.progressbar.WidthRequest = 250;
		this.progressbar.HeightRequest = 30;
		this.progressbar.Name = "progressbar";
		this.fixedFrame.Add(this.progressbar);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixedFrame[this.progressbar]));
		w3.X = 298;
		w3.Y = 657;
		// Container child fixedFrame.Gtk.Fixed+FixedChild
		this.buttonResetDraw = new global::Gtk.Button();
		this.buttonResetDraw.CanFocus = true;
		this.buttonResetDraw.Name = "buttonResetDraw";
		this.buttonResetDraw.UseUnderline = true;
		this.buttonResetDraw.Label = global::Mono.Unix.Catalog.GetString("Reset Draw");
		this.fixedFrame.Add(this.buttonResetDraw);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixedFrame[this.buttonResetDraw]));
		w4.X = 732;
		w4.Y = 643;
		this.Add(this.fixedFrame);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.KeyPressEvent += new global::Gtk.KeyPressEventHandler(this.OnKeyPressEvent);
		this.KeysChanged += new global::System.EventHandler(this.OnKeysChanged);
		this.drawingArea.KeyPressEvent += new global::Gtk.KeyPressEventHandler(this.OnDrawingAreaKeyPressEvent);
		this.drawingArea.MotionNotifyEvent += new global::Gtk.MotionNotifyEventHandler(this.OnDrawingAreaMotionNotifyEvent);
	}
}
