
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixedFrame;

	private global::Gtk.DrawingArea drawingArea;

	private global::Gtk.ComboBox comboboxColor;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.WidthRequest = 500;
		this.HeightRequest = 300;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DefaultWidth = 1000;
		this.DefaultHeight = 700;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixedFrame = new global::Gtk.Fixed();
		this.fixedFrame.Name = "fixedFrame";
		this.fixedFrame.HasWindow = false;
		// Container child fixedFrame.Gtk.Fixed+FixedChild
		this.drawingArea = new global::Gtk.DrawingArea();
		this.drawingArea.WidthRequest = 900;
		this.drawingArea.HeightRequest = 600;
		this.drawingArea.Name = "drawingArea";
		this.fixedFrame.Add(this.drawingArea);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixedFrame[this.drawingArea]));
		w1.X = 22;
		w1.Y = 18;
		// Container child fixedFrame.Gtk.Fixed+FixedChild
		this.comboboxColor = global::Gtk.ComboBox.NewText();
		this.comboboxColor.AppendText(global::Mono.Unix.Catalog.GetString("Black"));
		this.comboboxColor.AppendText(global::Mono.Unix.Catalog.GetString("White"));
		this.comboboxColor.AppendText(global::Mono.Unix.Catalog.GetString("Yellow"));
		this.comboboxColor.AppendText(global::Mono.Unix.Catalog.GetString("Green"));
		this.comboboxColor.AppendText(global::Mono.Unix.Catalog.GetString("Blue"));
		this.comboboxColor.AppendText(global::Mono.Unix.Catalog.GetString("Red"));
		this.comboboxColor.AppendText(global::Mono.Unix.Catalog.GetString("Pink"));
		this.comboboxColor.AppendText(global::Mono.Unix.Catalog.GetString("Brown"));
		this.comboboxColor.AppendText(global::Mono.Unix.Catalog.GetString("Orange"));
		this.comboboxColor.Name = "comboboxColor";
		this.comboboxColor.Active = 0;
		this.fixedFrame.Add(this.comboboxColor);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixedFrame[this.comboboxColor]));
		w2.X = 28;
		w2.Y = 654;
		this.Add(this.fixedFrame);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
